theme: jekyll-theme-modernist
title: John MacDonald
description: Awesome Network Engineer
permalink: /:collections/:title
twitter:
  username: jmacego
  card: summary
logo: /assets/jmac-profile.jpg
social:
  name: John MacDonald
  links:
    - https://www.linkedin.com/in/jmacego
    - https://github.com/jmacego
    - https://keybase.io/jmacego
jekyll-sitemap:
jekyll-feed:
jekyll_compose:
collections:
  projects:
    output: true
    permalink: /projects/:title
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "post"
plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache